services:
  app:
    build: .

    container_name: quiz-app

    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      - mongo
    
    volumes:
        - ./:/app
        - /app/node_modules

    restart: unless-stopped

  mongo:
    image: mongo:8

    container_name: quiz-db

    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: